### ISSUE TITLE
Test report formatting #1

### ISSUE THREAD

**Issue by paulhiggs** [cta-wave/WMAS2017#4] opened 2018-07-26 13:33 UTC
The test report shows the following...
![image](https://user-images.githubusercontent.com/3158807/43265480-d7de8006-90b6-11e8-8569-087329527911.png)
Not sure why TIMEOUT appears beside the test script filename

**Comment by louaybassbouss** [comment] 2018-08-06 13:55
@paulhiggs the tool used for creating the HTML report files from the JSON files generated by the test runner is [wptreport](https://www.npmjs.com/package/wptreport). It seems that the tool adds a label "TIMEOUT" to the test file if on the tests has the status TIMEOUT or NOTRUN. We will check if this is the correct behavior and come back to you. If it is not the expected behavior, we will file a bug.

**Comment by mlasak** [comment] 2018-08-17 12:37
@louaybassbouss Note that we have already adapted the tool to meet out requirements. The fork we are using is https://github.com/mlasak/wptreport Surely, we can change as we like or as required here.

**Comment by louaybassbouss** [comment] 2018-08-27 11:01
@paulhiggs I collected all information related to the overall status of a test file as well as the status of a sub test. The documentation of testharness.js is available in [testharness.js API](https://web-platform-tests.org/writing-tests/testharness-api.html). Section [Basic Usage](https://web-platform-tests.org/writing-tests/testharness-api.html#basic-usage) says that every sub test has as result `PASS`, `FAIL`, `TIMEOUT` and `NOTRUN`. These statuses are also listed in [Callback API](https://web-platform-tests.org/writing-tests/testharness-api.html#callback-api) section. According to [testharness.js#L1469](https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L1469), the status of a sub test will be initialized with `NOTRUN` and later set to one of the other values. This means if `TIMEOUT` is disabled (using `explicit_timeout` function described in [Setup](https://web-platform-tests.org/writing-tests/testharness-api.html#setup) section) and the test is not completed (neither `PASS` or `FAIL`), the status will remain `NOTRUN`. This is the interpretation after reading the source code of the testharness.js since there is no explanation in the documentation for the semantic of status `NOTRUN`. 

A test file may contain multiple sub tests and there is also an overall status for the test file which can be one of the following values: `OK`, `ERROR` and `TIMEOUT`. There is no further explanation for each of these statuses but from reading the code, the `ERROR` status will be set if an unexpected exception occurred (try catch block),[abort() function](https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L2294) is called, [timeout occurs when test in cleanup phase](https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L2167), test file [contains tests with duplicate names](https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L2337). The status will be [set to `OK`](https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L2344) at the end if it is not set yet (it was `null`) which means no `TIMEOUT` or `ERROR` occurred.

Please let me know if you still have questions

**Comment by paulhiggs** [comment] 2018-08-27 21:32
Thanks @louaybassbouss - we need to have some clear descriptions of these test status codes and the sub-test status codes. The people working with media devices (developing and testing them) are not likely to be the same as those developing browsers

**Comment by louaybassbouss** [comment] 2018-08-28 12:56
Thanks @paulhiggs for your comment. Description of test status codes are in this [README](https://github.com/cta-wave/WMAS2017/#remarks-to-testharnessjs-statuses). Test status codes such as `FAIL`, `TIMEOUT`, `NOTRUN` or `ERROR` are just indication that a problem occured. Media device people should look at the test case source code for detailed problem analysis.

**Closed by louaybassbouss** 2018-08-28 12:56 UTC
